server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: "sa"
    password: ""
    url: "jdbc:h2:./taskManager"

  jpa:
    show-sql: true

  # Настраиваем консоль Н2
  # Это позволит нам открыть её в браузере по указанному пути
  h2:
    console:
      enabled: true
      # Указываем путь, по которому будет открываться консоль
      path: /h2console/
      settings:
        web-allow-others: true

logging:
  level:
    root: INFO
    web: DEBUG
    # org.hibernate.type.descriptor.sql: TRACE
    # org.springframework.security: TRACE
    # io.hexlet.typoreporter: DEBUG

